// AUTO-GENERATED by scripts/monthly_report_builder.py — 직접 수정하지 마세요.
// 월별 집계 JSON을 정적 import 로 묶어 서버 번들에 포함시킵니다.
import r2026_03 from './2026-03.json';
import r2026_04 from './2026-04.json';
import r2026_05 from './2026-05.json';
import r2026_06 from './2026-06.json';
import r2026_07 from './2026-07.json';
import r2026_08 from './2026-08.json';

export const REPORT_FILES: unknown[] = [
    r2026_03,
    r2026_04,
    r2026_05,
    r2026_06,
    r2026_07,
    r2026_08,
];
